<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MS" failures="1" tests="5" name="DataProvider-Test" time="0.157" errors="0" timestamp="2024-01-11T01:30:08 IST">
  <testcase classname="practise.ClassFive" name="ClassFiveAddUser" time="0.011"/>
  <testcase classname="practise.ClassFive" name="ClassFiveAddUser" time="0.007"/>
  <testcase classname="practise.ClassFive" name="ClassFiveLogin" time="0.002"/>
  <testcase classname="practise.ClassFive" name="ClassFiveLogout" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at practise.ClassFive.ClassFiveLogout(ClassFive.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ClassFiveLogout -->
  <testcase classname="practise.ClassFive" name="ClassFiveSignUp" time="0.006"/>
</testsuite> <!-- DataProvider-Test -->
